name: 'Tests: node.js >= 20'

on: [pull_request, push]

jobs:
  tests:
    uses: ljharb/actions/.github/workflows/node.yml@main
    with:
      range: '^20.17 || >= 22.8'
      type: minors
      command: npm run tests-only
